package util;
// Generated 24-abr-2016 18:09:51 by Hibernate Tools 4.3.1.Final

/**
 * Evento generated by hbm2java
 */
public class Evento implements java.io.Serializable {

	private int idEvento;
	private Lugar lugar;
	private String nombreE;
	private String descripcion;
	private String fechaInicioFin;
	private String horaInicioFin;
	private String diaDeEvento;
	private String tipoEntrada;
	private String precios;
	private String foto;
	private String img;
	private String tipoEvento;

	public Evento() {
	}

	public Evento(int idEvento, Lugar lugar, String nombreE, String descripcion, String fechaInicioFin,
			String horaInicioFin, String diaDeEvento, String tipoEntrada, String precios, String foto, String img,
			String tipoEvento) {
		this.idEvento = idEvento;
		this.lugar = lugar;
		this.nombreE = nombreE;
		this.descripcion = descripcion;
		this.fechaInicioFin = fechaInicioFin;
		this.horaInicioFin = horaInicioFin;
		this.diaDeEvento = diaDeEvento;
		this.tipoEntrada = tipoEntrada;
		this.precios = precios;
		this.foto = foto;
		this.img = img;
		this.tipoEvento = tipoEvento;
	}

	public int getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(int idEvento) {
		this.idEvento = idEvento;
	}

	public Lugar getLugar() {
		return this.lugar;
	}

	public void setLugar(Lugar lugar) {
		this.lugar = lugar;
	}

	public String getNombreE() {
		return this.nombreE;
	}

	public void setNombreE(String nombreE) {
		this.nombreE = nombreE;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getFechaInicioFin() {
		return this.fechaInicioFin;
	}

	public void setFechaInicioFin(String fechaInicioFin) {
		this.fechaInicioFin = fechaInicioFin;
	}

	public String getHoraInicioFin() {
		return this.horaInicioFin;
	}

	public void setHoraInicioFin(String horaInicioFin) {
		this.horaInicioFin = horaInicioFin;
	}

	public String getDiaDeEvento() {
		return this.diaDeEvento;
	}

	public void setDiaDeEvento(String diaDeEvento) {
		this.diaDeEvento = diaDeEvento;
	}

	public String getTipoEntrada() {
		return this.tipoEntrada;
	}

	public void setTipoEntrada(String tipoEntrada) {
		this.tipoEntrada = tipoEntrada;
	}

	public String getPrecios() {
		return this.precios;
	}

	public void setPrecios(String precios) {
		this.precios = precios;
	}

	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public String getTipoEvento() {
		return this.tipoEvento;
	}

	public void setTipoEvento(String tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

}
